### ISSUE TITLE
A better way to install Powershell on Ubuntu 18.04

### ISSUE THREAD

**Issue by tohuw** [fvanroie/PS_OPNsense#2]
Hi, I happened across [your Wiki page on installing Powershell on Ubuntu 18.04](https://github.com/fvanroie/PS_OPNsense/wiki/Install-PowerShell-on-Ubuntu-18.04-beta). It works fine, but leaves you without a functional `curl`. So, here's a better way that lets you keep `libcurl4`:

1. Download the libicu57 dependancy:
```
cd /tmp
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu57_57.1-6ubuntu0.3_amd64.deb
```
2. Download the Debian package powershell_6.0.1-1.ubuntu.17.04_amd64.deb from the releases page onto the Ubuntu machine.
```
wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell_6.0.1-1.ubuntu.17.04_amd64.deb
```
3. Extract the PowerShell package and change the dependencies to libcurl4
```
dpkg-deb -R powershell_6.0.1-1.ubuntu.17.04_amd64.deb pwsh-patched
sudo apt install -y rpl
rpl libcurl3 libcurl4 pwsh-patched/DEBIAN/control
```
4. Re-Package the p package
```
dpkg-deb -b pwsh-patched pwsh-patched.deb
```
5. Install both packages in this order:
```
sudo apt install -fy ./libicu57_57.1-6ubuntu0.3_amd64.deb ./pwsh-patched.deb
```
Kudos to [Tim De Pauw](https://launchpad.net/~timdepauw) for [figuring out this exact libcurl3 dependency problem for another package](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294/comments/25), and @borgdylan for [suggesting this same fix for dotnet](https://github.com/dotnet/core-setup/issues/3875#issuecomment-383187576)

**Comment by fvanroie** [comment]
That worked out great and is indeed a much better solution. I have been struggling with that dependency myself.  Thanks so much for sharing. I updated that wiki page.
